language: generic
sudo: required

services:
  - docker

env:
  - DISTRO="centos:7"
  - DISTRO="fedora:latest"
  - DISTRO="fedora:rawhide"

matrix:
  allow_failures:
    - env: DISTRO="fedora:rawhide"

before_install:
  - sudo docker pull ${DISTRO}

install:
  - sudo docker run --detach --volume="${PWD}":/tmp/test --name `sed -e "s,:,-," <<< ${DISTRO}` ${DISTRO} sleep 600
  - tests/setup_test_container.sh ${DISTRO}

script:
  - sudo docker exec `sed -e "s,:,-," <<< ${DISTRO}` bash -c 'cd /tmp/test && ./runtests.sh -v'

after_script:
  - sudo docker stop `sed -e "s,:,-," <<< ${DISTRO}`
