---
- name: Install dev packages
  dnf:
    name:
    - gcc
    - python
    - python-devel
    - python-alembic
    - python-psycopg2
    - redhat-rpm-config
    state: present

- name: Install python packages from requirements.txt
  pip:
    requirements: /vagrant/requirements.txt

- name: Create the database
  command: python3 createdb.py
  args:
    chdir: /vagrant/
    creates: /vagrant/alembic.ini
