---
- name: Install dev packages
  dnf:
    name:
    - gcc
    - libpq-devel
    - python3
    - python3-devel
    - poetry
    # This breaks with Python 3 when installed from pip, it's terribly outdated.
    - python3-flask-xml-rpc
    - redhat-rpm-config
    # deps for running the tests
    - protobuf-compiler
    state: present

- name: Install python packages
  command:
    cmd: poetry install
    chdir: /vagrant

# Trust IPA's CA

- name: Get the content of the CA cert
  slurp:
    src: /etc/ipa/ca.crt
  register: ca_crt

- name: Get the CA certs file from certifi
  command: poetry run python -m certifi
  args:
    chdir: /vagrant
  register: certifi_cacert

- name: Put tinystage root CA in the list of CA's for certifi
  blockinfile:
    block: "{{ ca_crt.content | b64decode }}"
    path: "{{ certifi_cacert.stdout }}"

#

- name: register the application with oidc-register
  shell: poetry run oidc-register --debug --output-file /home/vagrant/client_secrets.json https://ipsilon.tinystage.test/idp/openidc/ https://mirrormanager2.tinystage.test/authorize
  args:
    chdir: /vagrant
    creates: /home/vagrant/client_secrets.json

- name: Install the config file
  copy:
    src: mirrormanager2.cfg
    dest: /home/vagrant/mirrormanager2.cfg
    mode: 0644
    owner: vagrant
    group: vagrant

- name: Create and populate the database
  command: poetry run python devel/populate.py
  args:
    chdir: /vagrant/
    creates: /var/tmp/mirrormanager2_dev.sqlite
  environment:
    MM2_CONFIG: '/home/vagrant/mirrormanager2.cfg'

- name: Install the systemd unit file for mirrormanager2 service
  copy:
    src: mirrormanager2.service
    dest: /etc/systemd/system/mirrormanager2.service
    mode: 0644

- name: Start mirrormanager2 service using systemd
  systemd:
    state: started
    name: mirrormanager2
    daemon_reload: yes
    enabled: yes
